### ISSUE TITLE
Поддержка экспорта данных активностей в вики репозитория по флагу -w

### ISSUE THREAD

**Issue by zmm** [OSLL/github_repo_commitment_calc#3]
Необходимо выгружать в отдельную таблицу список всех действий над всеми вики страницами указанного репозитория.

Колонки таблицы login, datetime, page, revision_id, action, diff

Что такое вики https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis

**Comment by HadronCollider** [comment]
В случае отсутствия wiki в репозитории (отключена / не существует) скрипт падает полностью (т.е. дальнейшие репо не обрабатываются) с ошибкой:
```
================= moevm/os_profiling =================
Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- git@github.com:moevm/os_profiling.wiki.git .//moevm/os_profiling
  stderr: 'Cloning into './/moevm/os_profiling'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'
```
