### ISSUE TITLE
Пофиксить дизайн аргументов командной строки

### ISSUE THREAD

**Issue by thehighestmath** [OSLL/github_repo_commitment_calc#47]
Issues, pull requests, invites -- имеют собственный флаг для логирования, а коммиты -- это когда флагов нет. Не совсем ясно зачем было сделано такое разделение. Предлагаю явно подавать флаг для логирования коммитов (например `--commits`) чтобы не было ощущения магии) 

Reference:
https://github.com/OSLL/github_repo_commitment_calc?tab=readme-ov-file#%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F

1. Логирование commits
```commandline
python3 main.py [-t, --token] token (github токен вместо token) [-l, --list]  list (list - строка пути к txt файлу со списком репозиториев) [-o, --out] out (out - название csv файла, в который будут помещены все логи) [-b, --branch] branch (branch - название конкретной ветки, откуда брать коммиты или all - логгировать все коммиты изо всех веток)
```
2. Логирование issues
```commandline
python3 main.py -i [-t, --token] token (github токен вместо token) [-l, --list]  list (list - строка пути к txt файлу со списком репозиториев) [-o, --out] out (out - название csv файла, в который будут помещены все логи)
```
3. Логирование pull requests
```commandline
python3 main.py -p [-t, --token] token (github токен вместо token) [-l, --list]  list (list - строка пути к txt файлу со списком репозиториев) [-o, --out] out (out - название csv файла, в который будут помещены все логи)
```
4. Логирование непринятых приглашений в репо
```commandline
python3 main.py --invites [-t, --token] token (github токен вместо token) [-l, --list]  list (list - строка пути к txt файлу со списком репозиториев) [-o, --out] out (out - название csv файла, в который будут помещены все логи)
```

**Comment by SaveliyBorivets** [comment]
Добавил короткий флаг '-c', а также длинные флаги к остальным опциям("--commits", "--issues" и т. д.).
Код поправил. Теперь, если нет флага логирования чего-либо, программа ничего не сделает(ранее происходило логирование коммитов).
Стоит ли поправить read.me файл в соответствии с изменениями? Если да, то пушить изменения в main или на ветку gitwiki?

**Comment by thehighestmath** [comment]
@SaveliyBorivets я бы поправил readme если изменилась команда описанная в файле, а она изменилась :)

**Comment by SaveliyBorivets** [comment]
Поправки внесены в ветку gitwiki
